name: Terraform CD
on:
  push:
    branches: [ master ]
    paths: [tf]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2     
    - name: Terraform Apply for Azure
      uses: ams0/terraform-apply-for-azure-action@v1
      with:
        terraform_version: 0.12.17
        # Azure Service Principal id
        arm_client_id: ${{ secrets.AZURE_SP_ID }}
        # Azure Service Principal secret
        arm_client_secret: ${{ secrets.AZURE_SP_SECRET }}
        # Azure Subscription id
        arm_subscription_id:  ${{ secrets.AZURE_SUBSCRIPTION }}
        # Azure Tenant id
        arm_tenant_id:  ${{ secrets.AZURE_TENANT }}
        # Azure Access key for state file storage account
        arm_access_key: ${{ secrets.TFSTATE_KEY }}
        path: tf
        variables: client_id=${{ secrets.AKS_SP_ID }},client_secret=${{ secrets.AKS_SP_SECRET }},mariadb_admin_user=${{ secrets.MARIADB_USER }},mariadb_admin_pass=${{ secrets.MARIADB_PASS }}
